# Generated by Django 4.2.5 on 2023-10-15 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='commande',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='produitcommande',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='souscategorie',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='categorie',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produitcommande',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='souscategorie',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
