# Generated by Django 4.2.5 on 2023-10-16 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_categorie_options_alter_commande_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitcommande',
            name='quantity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
