# Generated by Django 4.2.5 on 2023-10-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_produit_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom', models.CharField(max_length=60)),
                ('nom', models.CharField(max_length=60)),
                ('pays', models.CharField(max_length=60)),
                ('ville', models.CharField(max_length=100)),
                ('lieu', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=60)),
                ('phone', models.CharField(max_length=18)),
                ('codepostal', models.CharField(max_length=60)),
                ('mobile', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='categorie',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='IMG'),
        ),
    ]
