# Generated by Django 4.2.5 on 2023-10-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_newcommande_alter_categorie_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcommande',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcommande',
            name='email',
            field=models.EmailField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='newcommande',
            name='phone',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
